// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnnzwjwezfdyqqarfigv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhubnp3andlemZkeXFxYXJmaWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjc3MzQsImV4cCI6MjA1OTk0MzczNH0.4Zfn23r1bwrSvbxMUn89670-ofPqVx721GT5jzivFgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);